### ISSUE TITLE
unable to run dg_solo12 using rosrun .

### ISSUE THREAD

**Issue by shyamnsl** [machines-in-motion/dg_blmc_robots#18]
I get an error when running the executable dg_solo12 . 
`AttributeError: 'module' object has no attribute 'updateEntityClasses'`

I think the error is related a particular version of dynamic graph manager . can someone give the correct commits ?

![Screenshot from 2020-11-27 15-48-22](https://user-images.githubusercontent.com/73927822/100456246-0cc85900-30e6-11eb-8338-06b851e44014.png)

**Comment by MaximilienNaveau** [comment]
We have switch recently to ROS2... So this bug is deprecated.
I guess you need to update your code base.
